// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Services;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Entities.Dosen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dosens");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatKulId")
                        .HasColumnType("int");

                    b.Property<string>("NPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatKulId");

                    b.ToTable("Mahasiswas");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.MatKul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PengajarId")
                        .HasColumnType("int");

                    b.Property<int>("Sks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PengajarId");

                    b.ToTable("Matkuls");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Mahasiswa", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.MatKul", null)
                        .WithMany("Peserta")
                        .HasForeignKey("MatKulId");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.MatKul", b =>
                {
                    b.HasOne("WebApplication1.Models.Entities.Dosen", "Pengajar")
                        .WithMany()
                        .HasForeignKey("PengajarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengajar");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.MatKul", b =>
                {
                    b.Navigation("Peserta");
                });
#pragma warning restore 612, 618
        }
    }
}
